export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

// Activation Types
export const UPDATE_NAME_TOKEN = "UPDATE_NAME_TOKEN";
export const ACCOUNT_ACTIVATION_SUCCESS = "ACCOUNT_ACTIVATION_SUCCESS";
export const ACCOUNT_ACTIVATION_FAILED = "ACCOUNT_ACTIVATION_FAILED";
